export const guinchoTipos = [
    "GUINCHO PESADO NAO PADRAO",
    "PESADO COM PLAT HIDRAULICA MUNCK",
    "PESADO COM PLATAFORMA HIDRAULICA",
    "PESADO COM PLATAFORMA HIDRAULICA E BAND",
    "PESADO COM QUINTA RODA E BANDEJA",
    "PESADO COM TORRE E LANCA",
    "PESADO COM PLATAFORMA HIDRAULICA",
    "PESADO COM PLATAFORMA HIDRAULICA E LANCA",
    "PESADO COM QUINTA RODA E LANCA",
    "TECNICO PESADO PARA GUINCHO PESADO"
];